ManageIQ/manageiq-loggers

- lib/manageiq/loggers/container.rb
Add an option to ManageIQ::Loggers to control the underlying logdev
device buffering and default container logger to true.
> Add a .sync option to Loggers

- lib/manageiq/loggers.rb
- lib/manageiq/loggers/journald.rb
- manageiq-loggers.gemspec
Adds a class enabling users to add entries into the journald log with a standard ruby Logger interface.
> Add a Journald Logger

- lib/manageiq/loggers/cloud_watch.rb
- manageiq-loggers.gemspec
- spec/manageiq/cloud_watch_spec.rb
It is helpful for debugging purposes to see the logs on a pod as well as in Cloud Watch / Kibana.
> Broadcast the CloudWatch log messages to the Container logger as well

- .codeclimate.yml
See ManageIQ/manageiq#18840 for more information
Unfortunately there's no way to use a centralized .codeclimate, so we have to configure the configuration files individually.
> Specify a rubocop channel

- lib/manageiq/loggers/version.rb
- manageiq-loggers.gemspec
It looks like `Manageiq::Loggers::VERSION` should be `ManageIQ::Loggers::VERSION`, i.e. uppercase "IQ" at the end.
Also, I froze the constant, and updated the gemspec to match the change.
> Fix case in version file, freeze version constant

- lib/manageiq/loggers/journald.rb
- manageiq-loggers.gemspec
- spec/manageiq/journald_spec.rb
- spec/spec_helper.rb
Rather than using a simple `Systemd::Journal.print` for logging messages, I'd like to take advantage of  of the `Systemd::Journal.message` method, which lets us set various attributes.
Specifically, I'd like to set the following attributes for the following reasons:
* **syslog_identifier** - A trusted field that can be used by the `journal -t` option to filter logs by provider, as well as potential rsyslog configuration.
* ~~* **syslog_facility** - Another trusted field that could provide a way to query for ManageIQ related log entries, and another potential hook for rsyslog configuration.~~
* ~~**application** - Potentially useful as a way to get all manageiq related messages.~~
* **code_line** - Another trusted field we can use to show what generated the log entry.
* **code_file** - …
> Journald message improvements

- lib/manageiq/loggers/cloud_watch.rb
- spec/manageiq/cloud_watch_spec.rb
This reverts commit 772ae8f5027bafd210d579a081114c31f5ccc9e7.
log_group needs to be "platform" or "platform-dev" in order to have the correct permissions, switch back to preferring the ENV var.
RHIOPS-544
> Revert "Change CloudWatch log_group to be the namespace if it exists"

- lib/manageiq/loggers/container.rb
TPINVTRY-838
we need a way how to populate request-id In services without server.
needed for :
> Use Thread.current[:request_id] for logging request_id

- lib/manageiq/loggers/journald.rb
The caller_locations was incorrectly jumping to the bottom of the stack rather than the top of it, and thus was returning e.g. `bin/rails` as the calling file instead of the actual source file.
The top of the stack looks like:
```
caller location 0: /home/grare/adam/src/manageiq/manageiq-loggers/lib/manageiq/loggers/journald.rb:50:in `add'
caller location 1: /home/grare/adam/.gems/2.7.0/gems/activesupport-5.2.4.3/lib/active_support/logger.rb:27:in `block (2 levels) in broadcast'
caller location 2: /usr/lib/ruby/2.7.0/logger.rb:546:in `error'
caller location 3: /home/grare/adam/src/manageiq/manageiq/app/models/ext_management_system.rb:46:in `testing'
```
cc @djberg96
> Fix the handling of journald code_file/code_line

- lib/manageiq/loggers/journald.rb
Turns out there's also a `code_func` field in journald we can use. This PR updates the logging message to include it, via the `label` method.
https://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html
> Add code_func

- lib/manageiq/loggers/container.rb
- spec/manageiq/container_spec.rb
Built on top of #28 so the specs can pass.
Similar to https://github.com/ManageIQ/manageiq/pull/20883, this fixes the weird escaping in the container logger.
Example:
Before
```json
[1] pry(main)> $container_log.info("xxx < yyy > zzz")
{"@timestamp":"2020-12-09T14:59:14.307800 ","pid":39458,"tid":"3fdc05c2ffd0","level":"info","message":"xxx \u003c yyy \u003e zzz"}
```
After
```json
[1] pry(main)> $container_log.info("xxx < yyy > zzz")
{"@timestamp":"2020-12-09T14:58:30.909153 ","pid":39417,"tid":"3fd6d382ffd4","level":"info","message":"xxx < yyy > zzz"}
```
@bdunne Please review.
> Fix escaping of < and > in Container logger

- lib/manageiq/loggers/container.rb
- spec/manageiq/container_spec.rb
This call currently fails in specs because active_support/deprecation
was never required.  This commit adds in that, and also tests that
behavior.
Additionally, this prefers :request_id in thead local storage over
:current_request if both happen to be present, so as not to incur the
loading of active_support/deprecation in the normal case.
@bdunne Please review.  This should fix the current broken specs.
> Fix ActiveSupport::Deprecation call

- lib/manageiq/loggers/base.rb
- spec/manageiq/base_spec.rb
A recent issue had log lines that were 30K, and even that was proving to
be too long and relatively useless. journald limits log line length to
about 8kb, so this feels like a reasonable value.
@agrare Please review.
> Truncate log lines to 8Kb

- lib/manageiq/loggers/journald.rb
- spec/manageiq/journald_spec.rb
Make it simpler for callers to change the progname for all logger types by using progname rather than a different syslog identifier for journald logs.
> Use progname rather than syslog_identifier for journald logs

- .travis.yml
- lib/manageiq/loggers/base.rb
- spec/manageiq/base_spec.rb
@agrare Please review.
The reason for this is so we can set a class-level filter once for all calls to log_hashes on all instances of the loggers.  This will also prevent callers from accidentally not filtering when logging hashes.
> Add ability to set class-level and instance-level filters for log_hashes

- lib/manageiq/loggers/base.rb
- lib/manageiq/loggers/cloud_watch.rb
- spec/manageiq/base_spec.rb
As of Rails 7, active_support must be required before requiring any specific
core extensions.
@jrafanie Please review.
> Require active_support first

- lib/manageiq/loggers/base.rb
Fixes:
```
manageiq-loggers-1.0.0/lib/manageiq/loggers/base.rb:154: warning: global variable `$_miq_worker_current_msg' not initialized
```
Note, this happens whenever we log anything so it's super noisy if you're trying to fix ruby deprecation warnings in 2.7 for features removed in ruby 3.0 😉
> Check if the global is defined before trying to use it

- lib/manageiq/loggers/container.rb
- spec/manageiq/container_spec.rb
For some reason, the default format_datetime method returns a string
with a tailing space, which is fine when put into a format string, but
is strange when standalone in a JSON output.
@agrare Please review.
> Remove timestamp whitespace in container logger formatter

- lib/manageiq/loggers/cloud_watch.rb
Hey folks, long time no see :smile: 
We're happily using your logger, but got some issues with setting environment variables in certain contexts. Would it be possible to allow an alternative consumption of the params below instead of the ENV variables?
@Fryguy :wave:
> Allow passing the CW logger's configuration as kwargs

- lib/manageiq/loggers/journald.rb
Update the Journald logger's `Formatter#call` method to have consistent arguments with the standard Logger Formatter.  This allows for simpler subclasses of the Formatter by child classes that expect to have a standard call interface.
> Fix Journald::Formatter's arguments list

- manageiq-loggers.gemspec
ActiveSupport 7.1 both removed `ActiveSupport::Logger.broadcast` and introduced `BroadcastLogger` in the same release.  In order to support both <7.1 and >=7.1 we'll need to special case based on the version of activesupport.
For now this limits active_support to <7.1 and support will be added in a future release
> Fix missing ActiveSupport::Logger.broadcast

- .github/workflows/ci.yaml
- manageiq-loggers.gemspec
manageiq-style 1.5.2 requires rubocop 1.56.3, which, in turn, requires
Ruby >= 2.7. Thus, this commit also drops support for Ruby 2.6
This should resolve some of the Mend issues.
@jrafanie and @agrare Please review.  I'm not sure if this should get released as a 2.0 because of the Ruby 2.6 drop. Thoughts?
> Bump manageiq-style to >=1.5.2

- .github/workflows/ci.yaml
- Gemfile
- lib/manageiq/loggers/base.rb
- lib/manageiq/loggers/cloud_watch.rb
- lib/manageiq/loggers/journald.rb
- manageiq-loggers.gemspec
- spec/manageiq/cloud_watch_spec.rb
- spec/manageiq/journald_spec.rb
Rails has removed support for `ActiveSupport::Logger.broadcast` in the same release they added a `ActiveSupport::BroadcastLogger`.  This means in order to support both active_support < 7.1 and active_support >= 7.1 we need to special case this based on the gem version
TODO:
> Add a wrap method to support BroadcastLogger/ActiveSupport::Logger.broadcast

- CHANGELOG.md
- lib/manageiq/loggers/json_logger.rb
- spec/manageiq/json_logger_formatter_spec.rb
`ActiveSupport::Deprecation.warn` was removed in activesupport 7.2, and this has been deprecated for a number of releases including 1 major release.
> Drop the deprecated current_request.request_id

- CHANGELOG.md
- lib/manageiq/loggers/journald.rb
- spec/manageiq/journald_spec.rb
Depending on the way the logger is invoked (e.g. via a broadcast logger or not) the call stack is different.
If the caller_object is nil this was throwing an exception instead of just not setting the code_{line,file,func} properties of the `Systemd::Journal` message.
> Handle a nil caller_object in journald loggers

- lib/manageiq/loggers/journald.rb
- spec/manageiq/journald_spec.rb
Since it is up to the caller how the logger is invoked (e.g. directly or via a broadcast logger) we can't simply hard code the number of steps up the callstack to skip.
This attempts to dynamically determine the caller location.
> Determine caller location dynamically

- .github/workflows/ci.yaml
- Gemfile
- spec/manageiq/journald_spec.rb
Note, ruby 3.4 with rails 7.0 evokes this warning.  We can maintain 7.0 with 3.4 if we add mutex_m to our gemspec
until we can drop rails 7.0:
```
...gems/activesupport-7.0.8.7/lib/active_support/notifications/fanout.rb:3: warning: mutex_m was loaded from the standard library, but is not part of the default gems starting from Ruby 3.4.0.
You can add mutex_m to your Gemfile or gemspec to silence this warning.
```
Today I learned that filtering specs by "linux" still runs code outside of
tests. Code within the describe block is still evaluated before the tests
within it are excluded.  The require needs to be done within a let, before, or
an example. Instead, we can let the initialize do the require and make sure
that is run first by changing it to let!.
> Update ci matrix primarily for rails 7.2
